---
- hosts: raspi
  user: pi
  sudo: yes
  tasks:
    - name: copy sources.list
      copy: src=./sources.list dest=/home/pi/sources.list owner=pi group=sudo mode=0644

    - name: copy preferences
      copy: src=./preferences  dest=/home/pi/preferences  owner=pi group=sudo mode=0644

    - name: move setting files into /etc/apt
      shell: cp /home/pi/sources.list /etc/apt/ && cp /home/pi/preferences /etc/apt/

    - name: unarchive mt7610u
      unarchive: src=./mt7610u_wifi_sta_v3002_dpo_20130916.tar.bz2 dest=/home/pi/ owner=pi group=sudo mode=0644

    - name: clone patch
      git: dest=/home/pi/gist repo=https://gist.github.com/moutend/80e4aa9488eff395d06e

    - name: apply patch
      shell: /home/pi/gist/patch.sh

    - name: install packages
      shell: apt-get update && apt-get install -y ncurses-dev
